### ISSUE TITLE
Moodle: PuMuKIT Repository English: Series and Mm. Obj. without name

### ISSUE THREAD

**Issue by shermida** [teltek/PuMuKIT2-moodle-bundle#17]
**Steps:**
- Change Moodle language to English
- Select the Test PuMuKIT Integration course
- Click "Add an activity or resouce"
- In Resources select "Page" and press "Add"
- Fill in the name and in "Content" press the Media button (see picture below)
  ![media_button](https://cloud.githubusercontent.com/assets/19668673/16802904/5b4abf8e-4903-11e6-94fd-9188aaac526f.png)
- Click in "Browse repositories" and then PuMuKIT
- Click in Series >> My Series. There are two series. Click both to see the mm. obj. inside.
- Clic in Series >> Public Series. 
  ![undefined name2](https://cloud.githubusercontent.com/assets/19668673/16808612/76c4fc88-491d-11e6-997c-bc276dbb6e75.png)
- Change language to Spanish and repeat steps 2 to 8 
  ![spanish name](https://cloud.githubusercontent.com/assets/19668673/16808619/7ff80a70-491d-11e6-8d68-d147469d1c54.png)

**Result:**

If Moodle language is English, all series have the same name “Undefined” and the multimedia objects inside do not have a name, only the extension. However, if the language is Spanish, both Series and Mm. Obj. have name.

**Comment by Alfro** [comment]
This is because the language 'English' (In Moodle) does not exist for that particular PuMuKIT2 installation (where only Spanish is set as a valid _locale_).
When this happens, PuMuKIT returns the default locale value:

``` yml
parameters:
    ...
    locale: en      #This value needs to be configured correctly
    ...
```

The problem here is that the value in 'locale' is not included in the 'valid locales' in this installation:

``` yml
parameters:
    ...
    pumukit2.locales:
        - es
    ...
```

This is a configuration issue. The value should be 'es' for this particular installation.

**Comment by Alfro** [comment]
@shermida Once this is correctly configured, check it out again.

**Comment by shermida** [comment]
It is solved. I close the issue.
